### ISSUE TITLE
"GitHub Terms of Service"(Japanease) D.7 article indicates different section

### ISSUE THREAD

**Issue by mk7087** [github/site-policy#378] opened 2021-02-21 06:58 UTC
#### 1. What's the name of the policy?
[GitHub Terms of Service(Japanease)](https://docs.github.com/ja/github/site-policy/github-terms-of-service)

#### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
[D.7](https://docs.github.com/ja/github/site-policy/github-terms-of-service#7-moral-rights)

#### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).
No, I haven't opened any pull requests. I didn't know how to open a pull request for Non-english version policies.

#### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
> お客様は、完全性と帰属の権利も含めて、「サービス」の任意の部分に対してアップロード、公開、またはサブミットする「あなたのコンテンツ」について、すべての人格権を保持します。 ただしお客様は、GitHubが**セクション3.3**で付与された権利を合理的に行使できるようにする目的に限り、これらの権利を放棄し、GitHubに対してこれらの権利を主張しないことに同意するものとしますが、その目的以外ではこの限りではありません。

"セクション 3.3"(Section 3.3) doesn't exist. It is indicate "Section D.4"(セクション D.4) in English version. Should change "セクション 3.3" to "セクション D.4".

#### 5. Why do you think this section or language needs improvement?
Because, [provisions of D.7](https://docs.github.com/ja/github/site-policy/github-terms-of-service#7-moral-rights) doesn't make any effect in the Japanese version.

**Comment by nelsondani** [comment] 2021-02-26 20:54
- [ ] - **23000_40000_**

**Comment by nelsondani** [comment] 2021-02-26 20:55
> > - [x] - **23000_40000_****_`33000_**````

```

**Comment by nelsondani** [comment] 2021-02-27 03:07
>  #``30000`
Duplicate of #`

**Comment by pcihon** [comment] 2021-03-12 01:05
Thank you @mk7087 for catching this! I'm looking into fixing this internally.

**Comment by iontower** [comment] 2021-04-29 17:32
Ruben un TC

**Comment by falishaerriza** [comment] 2021-05-03 12:58
> #### 1. What's the name of the policy?
> [GitHub Terms of Service(Japanease)](https://docs.github.com/ja/github/site-policy/github-terms-of-service)
> 
> #### 2. Is this issue related to a specific section within one of our policies (e.g. the Terms of Service)? If so, please include a link to the section or subsection.
> [D.7](https://docs.github.com/ja/github/site-policy/github-terms-of-service#7-moral-rights)
> 
> #### 3. Did you already open a pull request? If so, please include a link to the PR in the [GitHub Docs repo](https://github.com/github/docs).
> No, I haven't opened any pull requests. I didn't know how to open a pull request for Non-english version policies.
> 
> #### 4. Sometimes it's easier to just put your feedback text into an issue. If that's how you'd prefer to contribute, this is the section to do that.
> > お客様は、完全性と帰属の権利も含めて、「サービス」の任意の部分に対してアップロード、公開、またはサブミットする「あなたのコンテンツ」について、すべての人格権を保持します。 ただしお客様は、GitHubが**セクション3.3**で付与された権利を合理的に行使できるようにする目的に限り、これらの権利を放棄し、GitHubに対してこれらの権利を主張しないことに同意するものとしますが、その目的以外ではこの限りではありません。
> 
> "セクション 3.3"(Section 3.3) doesn't exist. It is indicate "Section D.4"(セクション D.4) in English version. Should change "セクション 3.3" to "セクション D.4".
> 
> #### 5. Why do you think this section or language needs improvement?
> Because, [provisions of D.7](https://docs.github.com/ja/github/site-policy/github-terms-of-service#7-moral-rights) doesn't make any effect in the Japanese version.
>#378

**Comment by james7618891** [comment] 2021-05-26 18:08
Qqwer830316aaa@outlook.com

**Comment by 4970407078444002** [comment] 2021-11-09 03:10
2289687E02987

**Comment by 4970407078444002** [comment] 2021-11-09 03:11
Soumaredjiby94@gmail.com

**Comment by 4970407078444002** [comment] 2021-11-09 03:11
Soumare soumare djiby

**Comment by salamAbbass** [comment] 2021-11-25 23:17
#111

**Comment by salamAbbass** [comment] 2021-11-25 23:18
@
Duplicate of #

**Comment by vollmera** [comment] 2022-02-03 22:40
Thanks so much for this helpful feedback @mk7087! I'm belatedly noting this has been fixed. 

Closing this issue. 🎉

**Closed by vollmera** 2022-02-03 22:40 UTC
